when@prod:
    options:
        # Specify a fixed sample rate:
        traces_sample_rate: 1.0
        # Or provide a custom sampler:
        traces_sampler: 'sentry.callback.traces_sampler'
    sentry:
        dsn: '%env(SENTRY_DSN)%'
    monolog:
        handlers:
            sentry:
                type: service
                id: Sentry\Monolog\Handler
    services:
        sentry.callback.traces_sampler:
            class: 'App\Service\Sentry'
            factory: [ '@App\Service\Sentry', 'getTracesSampler' ]
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::ERROR