when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
    monolog:
        handlers:
            sentry:
                type: service
                id: Sentry\Monolog\Handler
    services:
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::ERROR